export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_PRODUCT_BYID_REQUEST = "GET_PRODUCT_BYID_REQUEST";
export const GET_PRODUCT_BYID_SUCCESS = "GET_PRODUCT_BYID_SUCCESS";
export const GET_PRODUCT_BYID_FAILURE = "GET_PRODUCT_BYID_FAILURE";

export const UPDATE_PRODUCT_BYID_REQUEST = "UPDATE_PRODUCT_BYID_REQUEST";
export const UPDATE_PRODUCT_BYID_SUCCESS = "UPDATE_PRODUCT_BYID_SUCCESS";
export const UPDATE_PRODUCT_BYID_FAILURE = "UPDATE_PRODUCT_BYID_FAILURE";

export const DELETE_PRODUCT_BYID_REQUEST = "DELETE_PRODUCT_BYID_REQUEST";
export const DELETE_PRODUCT_BYID_SUCCESS = "DELETE_PRODUCT_BYID_SUCCESS";
export const DELETE_PRODUCT_BYID_FAILURE = "DELETE_PRODUCT_BYID_FAILURE";
